### PR TITLE
Unification default values

### PR DESCRIPTION
**Pull request by lkudry**

### CODE REVIEW

**Comment by martin-g** [comment]
I'm afraid I'll need more information why those changes are needed to be able to decide whether to merge or not.

**Comment by lkudry** [comment]
I'm sorry. Default values between [javascript](https://github.com/l0rdn1kk0n/wicket-clientside-logging/blob/master/library/src/main/java/de/agilecoders/wicket/logging/js/clientside-logging.js#L276) and [java](https://github.com/l0rdn1kk0n/wicket-clientside-logging/blob/master/library/src/main/java/de/agilecoders/wicket/logging/util/DefaultValues.java#L11) are different. And because [java](https://github.com/l0rdn1kk0n/wicket-clientside-logging/blob/master/library/src/main/java/de/agilecoders/wicket/logging/ClientSideLoggingBehavior.java) promotes to JS only different options compared to default values, it is not possible to set some values to required format.

**Comment by martin-g** [comment]
Thanks!

**Comment by martin-g** [comment]
0.4.1 is traveling to Maven Central!

**Pull request merged**
